# Generated by Django 5.0 on 2024-01-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_employerprofile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='about',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
