# Generated by Django 5.0 on 2024-01-03 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=255)),
                ('responsibilities', models.CharField(max_length=255)),
                ('requirements', models.CharField(max_length=255)),
                ('conditions', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255)),
                ('in_favorites', models.ManyToManyField(blank=True, related_name='favorites_vacancy', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='vacancy_vac_publish_3929df_idx'), models.Index(fields=['name'], name='vacancy_vac_name_800eed_idx')],
            },
        ),
    ]
