# Generated by Django 5.0 on 2024-01-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancy_about_alter_vacancy_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='about',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=models.CharField(max_length=1000),
        ),
    ]
