# Generated by Django 5.0 on 2024-01-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_alter_vacancy_about_alter_vacancy_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
