# Generated by Django 5.0 on 2024-01-03 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('work_name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('telephone', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=100)),
                ('salary', models.IntegerField(blank=True)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=20)),
                ('date_of_birth', models.DateField(auto_now=True)),
                ('experience', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('in_favorites', models.ManyToManyField(blank=True, related_name='favorites_resume', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
