# Generated by Django 5.0 on 2024-01-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='date_of_birth',
        ),
    ]
